// AUTO-GENERATED by tools/extract_data.js
use phf::phf_map;

#[derive(Clone, Copy, Debug)]
pub struct AbilityData {
    pub num: i16,
    pub name: &'static str,
    pub description: &'static str,
}

pub static ABILITIES: phf::Map<&'static str, AbilityData> = phf_map! {
    "persistent" => AbilityData {
        num: -3,
        name: "Persistent",
        description: "",
    },
    "rebound" => AbilityData {
        num: -2,
        name: "Rebound",
        description: "",
    },
    "mountaineer" => AbilityData {
        num: -1,
        name: "Mountaineer",
        description: "",
    },
    "noability" => AbilityData {
        num: 0,
        name: "No Ability",
        description: "",
    },
    "stench" => AbilityData {
        num: 1,
        name: "Stench",
        description: "",
    },
    "drizzle" => AbilityData {
        num: 2,
        name: "Drizzle",
        description: "",
    },
    "speedboost" => AbilityData {
        num: 3,
        name: "Speed Boost",
        description: "",
    },
    "battlearmor" => AbilityData {
        num: 4,
        name: "Battle Armor",
        description: "",
    },
    "sturdy" => AbilityData {
        num: 5,
        name: "Sturdy",
        description: "",
    },
    "damp" => AbilityData {
        num: 6,
        name: "Damp",
        description: "",
    },
    "limber" => AbilityData {
        num: 7,
        name: "Limber",
        description: "",
    },
    "sandveil" => AbilityData {
        num: 8,
        name: "Sand Veil",
        description: "",
    },
    "static" => AbilityData {
        num: 9,
        name: "Static",
        description: "",
    },
    "voltabsorb" => AbilityData {
        num: 10,
        name: "Volt Absorb",
        description: "",
    },
    "waterabsorb" => AbilityData {
        num: 11,
        name: "Water Absorb",
        description: "",
    },
    "oblivious" => AbilityData {
        num: 12,
        name: "Oblivious",
        description: "",
    },
    "cloudnine" => AbilityData {
        num: 13,
        name: "Cloud Nine",
        description: "",
    },
    "compoundeyes" => AbilityData {
        num: 14,
        name: "Compound Eyes",
        description: "",
    },
    "insomnia" => AbilityData {
        num: 15,
        name: "Insomnia",
        description: "",
    },
    "colorchange" => AbilityData {
        num: 16,
        name: "Color Change",
        description: "",
    },
    "immunity" => AbilityData {
        num: 17,
        name: "Immunity",
        description: "",
    },
    "flashfire" => AbilityData {
        num: 18,
        name: "Flash Fire",
        description: "",
    },
    "shielddust" => AbilityData {
        num: 19,
        name: "Shield Dust",
        description: "",
    },
    "owntempo" => AbilityData {
        num: 20,
        name: "Own Tempo",
        description: "",
    },
    "suctioncups" => AbilityData {
        num: 21,
        name: "Suction Cups",
        description: "",
    },
    "intimidate" => AbilityData {
        num: 22,
        name: "Intimidate",
        description: "",
    },
    "shadowtag" => AbilityData {
        num: 23,
        name: "Shadow Tag",
        description: "",
    },
    "roughskin" => AbilityData {
        num: 24,
        name: "Rough Skin",
        description: "",
    },
    "wonderguard" => AbilityData {
        num: 25,
        name: "Wonder Guard",
        description: "",
    },
    "levitate" => AbilityData {
        num: 26,
        name: "Levitate",
        description: "",
    },
    "effectspore" => AbilityData {
        num: 27,
        name: "Effect Spore",
        description: "",
    },
    "synchronize" => AbilityData {
        num: 28,
        name: "Synchronize",
        description: "",
    },
    "clearbody" => AbilityData {
        num: 29,
        name: "Clear Body",
        description: "",
    },
    "naturalcure" => AbilityData {
        num: 30,
        name: "Natural Cure",
        description: "",
    },
    "lightningrod" => AbilityData {
        num: 31,
        name: "Lightning Rod",
        description: "",
    },
    "serenegrace" => AbilityData {
        num: 32,
        name: "Serene Grace",
        description: "",
    },
    "swiftswim" => AbilityData {
        num: 33,
        name: "Swift Swim",
        description: "",
    },
    "chlorophyll" => AbilityData {
        num: 34,
        name: "Chlorophyll",
        description: "",
    },
    "illuminate" => AbilityData {
        num: 35,
        name: "Illuminate",
        description: "",
    },
    "trace" => AbilityData {
        num: 36,
        name: "Trace",
        description: "",
    },
    "hugepower" => AbilityData {
        num: 37,
        name: "Huge Power",
        description: "",
    },
    "poisonpoint" => AbilityData {
        num: 38,
        name: "Poison Point",
        description: "",
    },
    "innerfocus" => AbilityData {
        num: 39,
        name: "Inner Focus",
        description: "",
    },
    "magmaarmor" => AbilityData {
        num: 40,
        name: "Magma Armor",
        description: "",
    },
    "waterveil" => AbilityData {
        num: 41,
        name: "Water Veil",
        description: "",
    },
    "magnetpull" => AbilityData {
        num: 42,
        name: "Magnet Pull",
        description: "",
    },
    "soundproof" => AbilityData {
        num: 43,
        name: "Soundproof",
        description: "",
    },
    "raindish" => AbilityData {
        num: 44,
        name: "Rain Dish",
        description: "",
    },
    "sandstream" => AbilityData {
        num: 45,
        name: "Sand Stream",
        description: "",
    },
    "pressure" => AbilityData {
        num: 46,
        name: "Pressure",
        description: "",
    },
    "thickfat" => AbilityData {
        num: 47,
        name: "Thick Fat",
        description: "",
    },
    "earlybird" => AbilityData {
        num: 48,
        name: "Early Bird",
        description: "",
    },
    "flamebody" => AbilityData {
        num: 49,
        name: "Flame Body",
        description: "",
    },
    "runaway" => AbilityData {
        num: 50,
        name: "Run Away",
        description: "",
    },
    "keeneye" => AbilityData {
        num: 51,
        name: "Keen Eye",
        description: "",
    },
    "hypercutter" => AbilityData {
        num: 52,
        name: "Hyper Cutter",
        description: "",
    },
    "pickup" => AbilityData {
        num: 53,
        name: "Pickup",
        description: "",
    },
    "truant" => AbilityData {
        num: 54,
        name: "Truant",
        description: "",
    },
    "hustle" => AbilityData {
        num: 55,
        name: "Hustle",
        description: "",
    },
    "cutecharm" => AbilityData {
        num: 56,
        name: "Cute Charm",
        description: "",
    },
    "plus" => AbilityData {
        num: 57,
        name: "Plus",
        description: "",
    },
    "minus" => AbilityData {
        num: 58,
        name: "Minus",
        description: "",
    },
    "forecast" => AbilityData {
        num: 59,
        name: "Forecast",
        description: "",
    },
    "stickyhold" => AbilityData {
        num: 60,
        name: "Sticky Hold",
        description: "",
    },
    "shedskin" => AbilityData {
        num: 61,
        name: "Shed Skin",
        description: "",
    },
    "guts" => AbilityData {
        num: 62,
        name: "Guts",
        description: "",
    },
    "marvelscale" => AbilityData {
        num: 63,
        name: "Marvel Scale",
        description: "",
    },
    "liquidooze" => AbilityData {
        num: 64,
        name: "Liquid Ooze",
        description: "",
    },
    "overgrow" => AbilityData {
        num: 65,
        name: "Overgrow",
        description: "",
    },
    "blaze" => AbilityData {
        num: 66,
        name: "Blaze",
        description: "",
    },
    "torrent" => AbilityData {
        num: 67,
        name: "Torrent",
        description: "",
    },
    "swarm" => AbilityData {
        num: 68,
        name: "Swarm",
        description: "",
    },
    "rockhead" => AbilityData {
        num: 69,
        name: "Rock Head",
        description: "",
    },
    "drought" => AbilityData {
        num: 70,
        name: "Drought",
        description: "",
    },
    "arenatrap" => AbilityData {
        num: 71,
        name: "Arena Trap",
        description: "",
    },
    "vitalspirit" => AbilityData {
        num: 72,
        name: "Vital Spirit",
        description: "",
    },
    "whitesmoke" => AbilityData {
        num: 73,
        name: "White Smoke",
        description: "",
    },
    "purepower" => AbilityData {
        num: 74,
        name: "Pure Power",
        description: "",
    },
    "shellarmor" => AbilityData {
        num: 75,
        name: "Shell Armor",
        description: "",
    },
    "airlock" => AbilityData {
        num: 76,
        name: "Air Lock",
        description: "",
    },
    "tangledfeet" => AbilityData {
        num: 77,
        name: "Tangled Feet",
        description: "",
    },
    "motordrive" => AbilityData {
        num: 78,
        name: "Motor Drive",
        description: "",
    },
    "rivalry" => AbilityData {
        num: 79,
        name: "Rivalry",
        description: "",
    },
    "steadfast" => AbilityData {
        num: 80,
        name: "Steadfast",
        description: "",
    },
    "snowcloak" => AbilityData {
        num: 81,
        name: "Snow Cloak",
        description: "",
    },
    "gluttony" => AbilityData {
        num: 82,
        name: "Gluttony",
        description: "",
    },
    "angerpoint" => AbilityData {
        num: 83,
        name: "Anger Point",
        description: "",
    },
    "unburden" => AbilityData {
        num: 84,
        name: "Unburden",
        description: "",
    },
    "heatproof" => AbilityData {
        num: 85,
        name: "Heatproof",
        description: "",
    },
    "simple" => AbilityData {
        num: 86,
        name: "Simple",
        description: "",
    },
    "dryskin" => AbilityData {
        num: 87,
        name: "Dry Skin",
        description: "",
    },
    "download" => AbilityData {
        num: 88,
        name: "Download",
        description: "",
    },
    "ironfist" => AbilityData {
        num: 89,
        name: "Iron Fist",
        description: "",
    },
    "poisonheal" => AbilityData {
        num: 90,
        name: "Poison Heal",
        description: "",
    },
    "adaptability" => AbilityData {
        num: 91,
        name: "Adaptability",
        description: "",
    },
    "skilllink" => AbilityData {
        num: 92,
        name: "Skill Link",
        description: "",
    },
    "hydration" => AbilityData {
        num: 93,
        name: "Hydration",
        description: "",
    },
    "solarpower" => AbilityData {
        num: 94,
        name: "Solar Power",
        description: "",
    },
    "quickfeet" => AbilityData {
        num: 95,
        name: "Quick Feet",
        description: "",
    },
    "normalize" => AbilityData {
        num: 96,
        name: "Normalize",
        description: "",
    },
    "sniper" => AbilityData {
        num: 97,
        name: "Sniper",
        description: "",
    },
    "magicguard" => AbilityData {
        num: 98,
        name: "Magic Guard",
        description: "",
    },
    "noguard" => AbilityData {
        num: 99,
        name: "No Guard",
        description: "",
    },
    "stall" => AbilityData {
        num: 100,
        name: "Stall",
        description: "",
    },
    "technician" => AbilityData {
        num: 101,
        name: "Technician",
        description: "",
    },
    "leafguard" => AbilityData {
        num: 102,
        name: "Leaf Guard",
        description: "",
    },
    "klutz" => AbilityData {
        num: 103,
        name: "Klutz",
        description: "",
    },
    "moldbreaker" => AbilityData {
        num: 104,
        name: "Mold Breaker",
        description: "",
    },
    "superluck" => AbilityData {
        num: 105,
        name: "Super Luck",
        description: "",
    },
    "aftermath" => AbilityData {
        num: 106,
        name: "Aftermath",
        description: "",
    },
    "anticipation" => AbilityData {
        num: 107,
        name: "Anticipation",
        description: "",
    },
    "forewarn" => AbilityData {
        num: 108,
        name: "Forewarn",
        description: "",
    },
    "unaware" => AbilityData {
        num: 109,
        name: "Unaware",
        description: "",
    },
    "tintedlens" => AbilityData {
        num: 110,
        name: "Tinted Lens",
        description: "",
    },
    "filter" => AbilityData {
        num: 111,
        name: "Filter",
        description: "",
    },
    "slowstart" => AbilityData {
        num: 112,
        name: "Slow Start",
        description: "",
    },
    "scrappy" => AbilityData {
        num: 113,
        name: "Scrappy",
        description: "",
    },
    "stormdrain" => AbilityData {
        num: 114,
        name: "Storm Drain",
        description: "",
    },
    "icebody" => AbilityData {
        num: 115,
        name: "Ice Body",
        description: "",
    },
    "solidrock" => AbilityData {
        num: 116,
        name: "Solid Rock",
        description: "",
    },
    "snowwarning" => AbilityData {
        num: 117,
        name: "Snow Warning",
        description: "",
    },
    "honeygather" => AbilityData {
        num: 118,
        name: "Honey Gather",
        description: "",
    },
    "frisk" => AbilityData {
        num: 119,
        name: "Frisk",
        description: "",
    },
    "reckless" => AbilityData {
        num: 120,
        name: "Reckless",
        description: "",
    },
    "multitype" => AbilityData {
        num: 121,
        name: "Multitype",
        description: "",
    },
    "flowergift" => AbilityData {
        num: 122,
        name: "Flower Gift",
        description: "",
    },
    "baddreams" => AbilityData {
        num: 123,
        name: "Bad Dreams",
        description: "",
    },
    "pickpocket" => AbilityData {
        num: 124,
        name: "Pickpocket",
        description: "",
    },
    "sheerforce" => AbilityData {
        num: 125,
        name: "Sheer Force",
        description: "",
    },
    "contrary" => AbilityData {
        num: 126,
        name: "Contrary",
        description: "",
    },
    "unnerve" => AbilityData {
        num: 127,
        name: "Unnerve",
        description: "",
    },
    "defiant" => AbilityData {
        num: 128,
        name: "Defiant",
        description: "",
    },
    "defeatist" => AbilityData {
        num: 129,
        name: "Defeatist",
        description: "",
    },
    "cursedbody" => AbilityData {
        num: 130,
        name: "Cursed Body",
        description: "",
    },
    "healer" => AbilityData {
        num: 131,
        name: "Healer",
        description: "",
    },
    "friendguard" => AbilityData {
        num: 132,
        name: "Friend Guard",
        description: "",
    },
    "weakarmor" => AbilityData {
        num: 133,
        name: "Weak Armor",
        description: "",
    },
    "heavymetal" => AbilityData {
        num: 134,
        name: "Heavy Metal",
        description: "",
    },
    "lightmetal" => AbilityData {
        num: 135,
        name: "Light Metal",
        description: "",
    },
    "multiscale" => AbilityData {
        num: 136,
        name: "Multiscale",
        description: "",
    },
    "toxicboost" => AbilityData {
        num: 137,
        name: "Toxic Boost",
        description: "",
    },
    "flareboost" => AbilityData {
        num: 138,
        name: "Flare Boost",
        description: "",
    },
    "harvest" => AbilityData {
        num: 139,
        name: "Harvest",
        description: "",
    },
    "telepathy" => AbilityData {
        num: 140,
        name: "Telepathy",
        description: "",
    },
    "moody" => AbilityData {
        num: 141,
        name: "Moody",
        description: "",
    },
    "overcoat" => AbilityData {
        num: 142,
        name: "Overcoat",
        description: "",
    },
    "poisontouch" => AbilityData {
        num: 143,
        name: "Poison Touch",
        description: "",
    },
    "regenerator" => AbilityData {
        num: 144,
        name: "Regenerator",
        description: "",
    },
    "bigpecks" => AbilityData {
        num: 145,
        name: "Big Pecks",
        description: "",
    },
    "sandrush" => AbilityData {
        num: 146,
        name: "Sand Rush",
        description: "",
    },
    "wonderskin" => AbilityData {
        num: 147,
        name: "Wonder Skin",
        description: "",
    },
    "analytic" => AbilityData {
        num: 148,
        name: "Analytic",
        description: "",
    },
    "illusion" => AbilityData {
        num: 149,
        name: "Illusion",
        description: "",
    },
    "imposter" => AbilityData {
        num: 150,
        name: "Imposter",
        description: "",
    },
    "infiltrator" => AbilityData {
        num: 151,
        name: "Infiltrator",
        description: "",
    },
    "mummy" => AbilityData {
        num: 152,
        name: "Mummy",
        description: "",
    },
    "moxie" => AbilityData {
        num: 153,
        name: "Moxie",
        description: "",
    },
    "justified" => AbilityData {
        num: 154,
        name: "Justified",
        description: "",
    },
    "rattled" => AbilityData {
        num: 155,
        name: "Rattled",
        description: "",
    },
    "magicbounce" => AbilityData {
        num: 156,
        name: "Magic Bounce",
        description: "",
    },
    "sapsipper" => AbilityData {
        num: 157,
        name: "Sap Sipper",
        description: "",
    },
    "prankster" => AbilityData {
        num: 158,
        name: "Prankster",
        description: "",
    },
    "sandforce" => AbilityData {
        num: 159,
        name: "Sand Force",
        description: "",
    },
    "ironbarbs" => AbilityData {
        num: 160,
        name: "Iron Barbs",
        description: "",
    },
    "zenmode" => AbilityData {
        num: 161,
        name: "Zen Mode",
        description: "",
    },
    "victorystar" => AbilityData {
        num: 162,
        name: "Victory Star",
        description: "",
    },
    "turboblaze" => AbilityData {
        num: 163,
        name: "Turboblaze",
        description: "",
    },
    "teravolt" => AbilityData {
        num: 164,
        name: "Teravolt",
        description: "",
    },
    "aromaveil" => AbilityData {
        num: 165,
        name: "Aroma Veil",
        description: "",
    },
    "flowerveil" => AbilityData {
        num: 166,
        name: "Flower Veil",
        description: "",
    },
    "cheekpouch" => AbilityData {
        num: 167,
        name: "Cheek Pouch",
        description: "",
    },
    "protean" => AbilityData {
        num: 168,
        name: "Protean",
        description: "",
    },
    "furcoat" => AbilityData {
        num: 169,
        name: "Fur Coat",
        description: "",
    },
    "magician" => AbilityData {
        num: 170,
        name: "Magician",
        description: "",
    },
    "bulletproof" => AbilityData {
        num: 171,
        name: "Bulletproof",
        description: "",
    },
    "competitive" => AbilityData {
        num: 172,
        name: "Competitive",
        description: "",
    },
    "strongjaw" => AbilityData {
        num: 173,
        name: "Strong Jaw",
        description: "",
    },
    "refrigerate" => AbilityData {
        num: 174,
        name: "Refrigerate",
        description: "",
    },
    "sweetveil" => AbilityData {
        num: 175,
        name: "Sweet Veil",
        description: "",
    },
    "stancechange" => AbilityData {
        num: 176,
        name: "Stance Change",
        description: "",
    },
    "galewings" => AbilityData {
        num: 177,
        name: "Gale Wings",
        description: "",
    },
    "megalauncher" => AbilityData {
        num: 178,
        name: "Mega Launcher",
        description: "",
    },
    "grasspelt" => AbilityData {
        num: 179,
        name: "Grass Pelt",
        description: "",
    },
    "symbiosis" => AbilityData {
        num: 180,
        name: "Symbiosis",
        description: "",
    },
    "toughclaws" => AbilityData {
        num: 181,
        name: "Tough Claws",
        description: "",
    },
    "pixilate" => AbilityData {
        num: 182,
        name: "Pixilate",
        description: "",
    },
    "gooey" => AbilityData {
        num: 183,
        name: "Gooey",
        description: "",
    },
    "aerilate" => AbilityData {
        num: 184,
        name: "Aerilate",
        description: "",
    },
    "parentalbond" => AbilityData {
        num: 185,
        name: "Parental Bond",
        description: "",
    },
    "darkaura" => AbilityData {
        num: 186,
        name: "Dark Aura",
        description: "",
    },
    "fairyaura" => AbilityData {
        num: 187,
        name: "Fairy Aura",
        description: "",
    },
    "aurabreak" => AbilityData {
        num: 188,
        name: "Aura Break",
        description: "",
    },
    "primordialsea" => AbilityData {
        num: 189,
        name: "Primordial Sea",
        description: "",
    },
    "desolateland" => AbilityData {
        num: 190,
        name: "Desolate Land",
        description: "",
    },
    "deltastream" => AbilityData {
        num: 191,
        name: "Delta Stream",
        description: "",
    },
    "stamina" => AbilityData {
        num: 192,
        name: "Stamina",
        description: "",
    },
    "wimpout" => AbilityData {
        num: 193,
        name: "Wimp Out",
        description: "",
    },
    "emergencyexit" => AbilityData {
        num: 194,
        name: "Emergency Exit",
        description: "",
    },
    "watercompaction" => AbilityData {
        num: 195,
        name: "Water Compaction",
        description: "",
    },
    "merciless" => AbilityData {
        num: 196,
        name: "Merciless",
        description: "",
    },
    "shieldsdown" => AbilityData {
        num: 197,
        name: "Shields Down",
        description: "",
    },
    "stakeout" => AbilityData {
        num: 198,
        name: "Stakeout",
        description: "",
    },
    "waterbubble" => AbilityData {
        num: 199,
        name: "Water Bubble",
        description: "",
    },
    "steelworker" => AbilityData {
        num: 200,
        name: "Steelworker",
        description: "",
    },
    "berserk" => AbilityData {
        num: 201,
        name: "Berserk",
        description: "",
    },
    "slushrush" => AbilityData {
        num: 202,
        name: "Slush Rush",
        description: "",
    },
    "longreach" => AbilityData {
        num: 203,
        name: "Long Reach",
        description: "",
    },
    "liquidvoice" => AbilityData {
        num: 204,
        name: "Liquid Voice",
        description: "",
    },
    "triage" => AbilityData {
        num: 205,
        name: "Triage",
        description: "",
    },
    "galvanize" => AbilityData {
        num: 206,
        name: "Galvanize",
        description: "",
    },
    "surgesurfer" => AbilityData {
        num: 207,
        name: "Surge Surfer",
        description: "",
    },
    "schooling" => AbilityData {
        num: 208,
        name: "Schooling",
        description: "",
    },
    "disguise" => AbilityData {
        num: 209,
        name: "Disguise",
        description: "",
    },
    "battlebond" => AbilityData {
        num: 210,
        name: "Battle Bond",
        description: "",
    },
    "powerconstruct" => AbilityData {
        num: 211,
        name: "Power Construct",
        description: "",
    },
    "corrosion" => AbilityData {
        num: 212,
        name: "Corrosion",
        description: "",
    },
    "comatose" => AbilityData {
        num: 213,
        name: "Comatose",
        description: "",
    },
    "queenlymajesty" => AbilityData {
        num: 214,
        name: "Queenly Majesty",
        description: "",
    },
    "innardsout" => AbilityData {
        num: 215,
        name: "Innards Out",
        description: "",
    },
    "dancer" => AbilityData {
        num: 216,
        name: "Dancer",
        description: "",
    },
    "battery" => AbilityData {
        num: 217,
        name: "Battery",
        description: "",
    },
    "fluffy" => AbilityData {
        num: 218,
        name: "Fluffy",
        description: "",
    },
    "dazzling" => AbilityData {
        num: 219,
        name: "Dazzling",
        description: "",
    },
    "soulheart" => AbilityData {
        num: 220,
        name: "Soul-Heart",
        description: "",
    },
    "tanglinghair" => AbilityData {
        num: 221,
        name: "Tangling Hair",
        description: "",
    },
    "receiver" => AbilityData {
        num: 222,
        name: "Receiver",
        description: "",
    },
    "powerofalchemy" => AbilityData {
        num: 223,
        name: "Power of Alchemy",
        description: "",
    },
    "beastboost" => AbilityData {
        num: 224,
        name: "Beast Boost",
        description: "",
    },
    "rkssystem" => AbilityData {
        num: 225,
        name: "RKS System",
        description: "",
    },
    "electricsurge" => AbilityData {
        num: 226,
        name: "Electric Surge",
        description: "",
    },
    "psychicsurge" => AbilityData {
        num: 227,
        name: "Psychic Surge",
        description: "",
    },
    "mistysurge" => AbilityData {
        num: 228,
        name: "Misty Surge",
        description: "",
    },
    "grassysurge" => AbilityData {
        num: 229,
        name: "Grassy Surge",
        description: "",
    },
    "fullmetalbody" => AbilityData {
        num: 230,
        name: "Full Metal Body",
        description: "",
    },
    "shadowshield" => AbilityData {
        num: 231,
        name: "Shadow Shield",
        description: "",
    },
    "prismarmor" => AbilityData {
        num: 232,
        name: "Prism Armor",
        description: "",
    },
    "neuroforce" => AbilityData {
        num: 233,
        name: "Neuroforce",
        description: "",
    },
    "intrepidsword" => AbilityData {
        num: 234,
        name: "Intrepid Sword",
        description: "",
    },
    "dauntlessshield" => AbilityData {
        num: 235,
        name: "Dauntless Shield",
        description: "",
    },
    "libero" => AbilityData {
        num: 236,
        name: "Libero",
        description: "",
    },
    "ballfetch" => AbilityData {
        num: 237,
        name: "Ball Fetch",
        description: "",
    },
    "cottondown" => AbilityData {
        num: 238,
        name: "Cotton Down",
        description: "",
    },
    "propellertail" => AbilityData {
        num: 239,
        name: "Propeller Tail",
        description: "",
    },
    "mirrorarmor" => AbilityData {
        num: 240,
        name: "Mirror Armor",
        description: "",
    },
    "gulpmissile" => AbilityData {
        num: 241,
        name: "Gulp Missile",
        description: "",
    },
    "stalwart" => AbilityData {
        num: 242,
        name: "Stalwart",
        description: "",
    },
    "steamengine" => AbilityData {
        num: 243,
        name: "Steam Engine",
        description: "",
    },
    "punkrock" => AbilityData {
        num: 244,
        name: "Punk Rock",
        description: "",
    },
    "sandspit" => AbilityData {
        num: 245,
        name: "Sand Spit",
        description: "",
    },
    "icescales" => AbilityData {
        num: 246,
        name: "Ice Scales",
        description: "",
    },
    "ripen" => AbilityData {
        num: 247,
        name: "Ripen",
        description: "",
    },
    "iceface" => AbilityData {
        num: 248,
        name: "Ice Face",
        description: "",
    },
    "powerspot" => AbilityData {
        num: 249,
        name: "Power Spot",
        description: "",
    },
    "mimicry" => AbilityData {
        num: 250,
        name: "Mimicry",
        description: "",
    },
    "screencleaner" => AbilityData {
        num: 251,
        name: "Screen Cleaner",
        description: "",
    },
    "steelyspirit" => AbilityData {
        num: 252,
        name: "Steely Spirit",
        description: "",
    },
    "perishbody" => AbilityData {
        num: 253,
        name: "Perish Body",
        description: "",
    },
    "wanderingspirit" => AbilityData {
        num: 254,
        name: "Wandering Spirit",
        description: "",
    },
    "gorillatactics" => AbilityData {
        num: 255,
        name: "Gorilla Tactics",
        description: "",
    },
    "neutralizinggas" => AbilityData {
        num: 256,
        name: "Neutralizing Gas",
        description: "",
    },
    "pastelveil" => AbilityData {
        num: 257,
        name: "Pastel Veil",
        description: "",
    },
    "hungerswitch" => AbilityData {
        num: 258,
        name: "Hunger Switch",
        description: "",
    },
    "quickdraw" => AbilityData {
        num: 259,
        name: "Quick Draw",
        description: "",
    },
    "unseenfist" => AbilityData {
        num: 260,
        name: "Unseen Fist",
        description: "",
    },
    "curiousmedicine" => AbilityData {
        num: 261,
        name: "Curious Medicine",
        description: "",
    },
    "transistor" => AbilityData {
        num: 262,
        name: "Transistor",
        description: "",
    },
    "dragonsmaw" => AbilityData {
        num: 263,
        name: "Dragon's Maw",
        description: "",
    },
    "chillingneigh" => AbilityData {
        num: 264,
        name: "Chilling Neigh",
        description: "",
    },
    "grimneigh" => AbilityData {
        num: 265,
        name: "Grim Neigh",
        description: "",
    },
    "asoneglastrier" => AbilityData {
        num: 266,
        name: "As One (Glastrier)",
        description: "",
    },
    "asonespectrier" => AbilityData {
        num: 267,
        name: "As One (Spectrier)",
        description: "",
    },
    "lingeringaroma" => AbilityData {
        num: 268,
        name: "Lingering Aroma",
        description: "",
    },
    "seedsower" => AbilityData {
        num: 269,
        name: "Seed Sower",
        description: "",
    },
    "thermalexchange" => AbilityData {
        num: 270,
        name: "Thermal Exchange",
        description: "",
    },
    "angershell" => AbilityData {
        num: 271,
        name: "Anger Shell",
        description: "",
    },
    "purifyingsalt" => AbilityData {
        num: 272,
        name: "Purifying Salt",
        description: "",
    },
    "wellbakedbody" => AbilityData {
        num: 273,
        name: "Well-Baked Body",
        description: "",
    },
    "windrider" => AbilityData {
        num: 274,
        name: "Wind Rider",
        description: "",
    },
    "guarddog" => AbilityData {
        num: 275,
        name: "Guard Dog",
        description: "",
    },
    "rockypayload" => AbilityData {
        num: 276,
        name: "Rocky Payload",
        description: "",
    },
    "windpower" => AbilityData {
        num: 277,
        name: "Wind Power",
        description: "",
    },
    "zerotohero" => AbilityData {
        num: 278,
        name: "Zero to Hero",
        description: "",
    },
    "commander" => AbilityData {
        num: 279,
        name: "Commander",
        description: "",
    },
    "electromorphosis" => AbilityData {
        num: 280,
        name: "Electromorphosis",
        description: "",
    },
    "protosynthesis" => AbilityData {
        num: 281,
        name: "Protosynthesis",
        description: "",
    },
    "quarkdrive" => AbilityData {
        num: 282,
        name: "Quark Drive",
        description: "",
    },
    "goodasgold" => AbilityData {
        num: 283,
        name: "Good as Gold",
        description: "",
    },
    "beadsofruin" => AbilityData {
        num: 284,
        name: "Beads of Ruin",
        description: "",
    },
    "tabletsofruin" => AbilityData {
        num: 284,
        name: "Tablets of Ruin",
        description: "",
    },
    "vesselofruin" => AbilityData {
        num: 284,
        name: "Vessel of Ruin",
        description: "",
    },
    "swordofruin" => AbilityData {
        num: 285,
        name: "Sword of Ruin",
        description: "",
    },
    "orichalcumpulse" => AbilityData {
        num: 288,
        name: "Orichalcum Pulse",
        description: "",
    },
    "hadronengine" => AbilityData {
        num: 289,
        name: "Hadron Engine",
        description: "",
    },
    "opportunist" => AbilityData {
        num: 290,
        name: "Opportunist",
        description: "",
    },
    "cudchew" => AbilityData {
        num: 291,
        name: "Cud Chew",
        description: "",
    },
    "sharpness" => AbilityData {
        num: 292,
        name: "Sharpness",
        description: "",
    },
    "supremeoverlord" => AbilityData {
        num: 293,
        name: "Supreme Overlord",
        description: "",
    },
    "costar" => AbilityData {
        num: 294,
        name: "Costar",
        description: "",
    },
    "toxicdebris" => AbilityData {
        num: 295,
        name: "Toxic Debris",
        description: "",
    },
    "armortail" => AbilityData {
        num: 296,
        name: "Armor Tail",
        description: "",
    },
    "eartheater" => AbilityData {
        num: 297,
        name: "Earth Eater",
        description: "",
    },
    "myceliummight" => AbilityData {
        num: 298,
        name: "Mycelium Might",
        description: "",
    },
    "hospitality" => AbilityData {
        num: 299,
        name: "Hospitality",
        description: "",
    },
    "mindseye" => AbilityData {
        num: 300,
        name: "Mind's Eye",
        description: "",
    },
    "embodyaspectteal" => AbilityData {
        num: 301,
        name: "Embody Aspect (Teal)",
        description: "",
    },
    "embodyaspectwellspring" => AbilityData {
        num: 302,
        name: "Embody Aspect (Wellspring)",
        description: "",
    },
    "embodyaspecthearthflame" => AbilityData {
        num: 303,
        name: "Embody Aspect (Hearthflame)",
        description: "",
    },
    "embodyaspectcornerstone" => AbilityData {
        num: 304,
        name: "Embody Aspect (Cornerstone)",
        description: "",
    },
    "toxicchain" => AbilityData {
        num: 305,
        name: "Toxic Chain",
        description: "",
    },
    "supersweetsyrup" => AbilityData {
        num: 306,
        name: "Supersweet Syrup",
        description: "",
    },
    "terashift" => AbilityData {
        num: 307,
        name: "Tera Shift",
        description: "",
    },
    "terashell" => AbilityData {
        num: 308,
        name: "Tera Shell",
        description: "",
    },
    "teraformzero" => AbilityData {
        num: 309,
        name: "Teraform Zero",
        description: "",
    },
    "poisonpuppeteer" => AbilityData {
        num: 310,
        name: "Poison Puppeteer",
        description: "",
    },
};
