// AUTO-GENERATED by tools/extract_data.js
use phf::phf_map;

#[derive(Clone, Copy, Debug)]
pub struct ItemData {
    pub num: i16,
    pub name: &'static str,
    pub description: &'static str,
}

pub static ITEMS: phf::Map<&'static str, ItemData> = phf_map! {
    "vilevial" => ItemData {
        num: -2,
        name: "Vile Vial",
        description: "",
    },
    "crucibellite" => ItemData {
        num: -1,
        name: "Crucibellite",
        description: "",
    },
    "berserkgene" => ItemData {
        num: 0,
        name: "Berserk Gene",
        description: "",
    },
    "masterball" => ItemData {
        num: 1,
        name: "Master Ball",
        description: "",
    },
    "ultraball" => ItemData {
        num: 2,
        name: "Ultra Ball",
        description: "",
    },
    "greatball" => ItemData {
        num: 3,
        name: "Great Ball",
        description: "",
    },
    "pokeball" => ItemData {
        num: 4,
        name: "Poke Ball",
        description: "",
    },
    "safariball" => ItemData {
        num: 5,
        name: "Safari Ball",
        description: "",
    },
    "netball" => ItemData {
        num: 6,
        name: "Net Ball",
        description: "",
    },
    "diveball" => ItemData {
        num: 7,
        name: "Dive Ball",
        description: "",
    },
    "nestball" => ItemData {
        num: 8,
        name: "Nest Ball",
        description: "",
    },
    "repeatball" => ItemData {
        num: 9,
        name: "Repeat Ball",
        description: "",
    },
    "timerball" => ItemData {
        num: 10,
        name: "Timer Ball",
        description: "",
    },
    "luxuryball" => ItemData {
        num: 11,
        name: "Luxury Ball",
        description: "",
    },
    "premierball" => ItemData {
        num: 12,
        name: "Premier Ball",
        description: "",
    },
    "duskball" => ItemData {
        num: 13,
        name: "Dusk Ball",
        description: "",
    },
    "healball" => ItemData {
        num: 14,
        name: "Heal Ball",
        description: "",
    },
    "quickball" => ItemData {
        num: 15,
        name: "Quick Ball",
        description: "",
    },
    "cherishball" => ItemData {
        num: 16,
        name: "Cherish Ball",
        description: "",
    },
    "berryjuice" => ItemData {
        num: 43,
        name: "Berry Juice",
        description: "",
    },
    "sunstone" => ItemData {
        num: 80,
        name: "Sun Stone",
        description: "",
    },
    "moonstone" => ItemData {
        num: 81,
        name: "Moon Stone",
        description: "",
    },
    "firestone" => ItemData {
        num: 82,
        name: "Fire Stone",
        description: "",
    },
    "thunderstone" => ItemData {
        num: 83,
        name: "Thunder Stone",
        description: "",
    },
    "waterstone" => ItemData {
        num: 84,
        name: "Water Stone",
        description: "",
    },
    "leafstone" => ItemData {
        num: 85,
        name: "Leaf Stone",
        description: "",
    },
    "rootfossil" => ItemData {
        num: 99,
        name: "Root Fossil",
        description: "",
    },
    "clawfossil" => ItemData {
        num: 100,
        name: "Claw Fossil",
        description: "",
    },
    "helixfossil" => ItemData {
        num: 101,
        name: "Helix Fossil",
        description: "",
    },
    "domefossil" => ItemData {
        num: 102,
        name: "Dome Fossil",
        description: "",
    },
    "oldamber" => ItemData {
        num: 103,
        name: "Old Amber",
        description: "",
    },
    "armorfossil" => ItemData {
        num: 104,
        name: "Armor Fossil",
        description: "",
    },
    "skullfossil" => ItemData {
        num: 105,
        name: "Skull Fossil",
        description: "",
    },
    "rarebone" => ItemData {
        num: 106,
        name: "Rare Bone",
        description: "",
    },
    "shinystone" => ItemData {
        num: 107,
        name: "Shiny Stone",
        description: "",
    },
    "duskstone" => ItemData {
        num: 108,
        name: "Dusk Stone",
        description: "",
    },
    "dawnstone" => ItemData {
        num: 109,
        name: "Dawn Stone",
        description: "",
    },
    "ovalstone" => ItemData {
        num: 110,
        name: "Oval Stone",
        description: "",
    },
    "griseousorb" => ItemData {
        num: 112,
        name: "Griseous Orb",
        description: "",
    },
    "dousedrive" => ItemData {
        num: 116,
        name: "Douse Drive",
        description: "",
    },
    "shockdrive" => ItemData {
        num: 117,
        name: "Shock Drive",
        description: "",
    },
    "burndrive" => ItemData {
        num: 118,
        name: "Burn Drive",
        description: "",
    },
    "chilldrive" => ItemData {
        num: 119,
        name: "Chill Drive",
        description: "",
    },
    "adamantorb" => ItemData {
        num: 135,
        name: "Adamant Orb",
        description: "",
    },
    "lustrousorb" => ItemData {
        num: 136,
        name: "Lustrous Orb",
        description: "",
    },
    "mail" => ItemData {
        num: 137,
        name: "Mail",
        description: "",
    },
    "cheriberry" => ItemData {
        num: 149,
        name: "Cheri Berry",
        description: "",
    },
    "przcureberry" => ItemData {
        num: 149,
        name: "PRZ Cure Berry",
        description: "",
    },
    "chestoberry" => ItemData {
        num: 150,
        name: "Chesto Berry",
        description: "",
    },
    "mintberry" => ItemData {
        num: 150,
        name: "Mint Berry",
        description: "",
    },
    "pechaberry" => ItemData {
        num: 151,
        name: "Pecha Berry",
        description: "",
    },
    "psncureberry" => ItemData {
        num: 151,
        name: "PSN Cure Berry",
        description: "",
    },
    "iceberry" => ItemData {
        num: 152,
        name: "Ice Berry",
        description: "",
    },
    "rawstberry" => ItemData {
        num: 152,
        name: "Rawst Berry",
        description: "",
    },
    "aspearberry" => ItemData {
        num: 153,
        name: "Aspear Berry",
        description: "",
    },
    "burntberry" => ItemData {
        num: 153,
        name: "Burnt Berry",
        description: "",
    },
    "leppaberry" => ItemData {
        num: 154,
        name: "Leppa Berry",
        description: "",
    },
    "mysteryberry" => ItemData {
        num: 154,
        name: "Mystery Berry",
        description: "",
    },
    "berry" => ItemData {
        num: 155,
        name: "Berry",
        description: "",
    },
    "oranberry" => ItemData {
        num: 155,
        name: "Oran Berry",
        description: "",
    },
    "bitterberry" => ItemData {
        num: 156,
        name: "Bitter Berry",
        description: "",
    },
    "persimberry" => ItemData {
        num: 156,
        name: "Persim Berry",
        description: "",
    },
    "lumberry" => ItemData {
        num: 157,
        name: "Lum Berry",
        description: "",
    },
    "miracleberry" => ItemData {
        num: 157,
        name: "Miracle Berry",
        description: "",
    },
    "goldberry" => ItemData {
        num: 158,
        name: "Gold Berry",
        description: "",
    },
    "sitrusberry" => ItemData {
        num: 158,
        name: "Sitrus Berry",
        description: "",
    },
    "figyberry" => ItemData {
        num: 159,
        name: "Figy Berry",
        description: "",
    },
    "wikiberry" => ItemData {
        num: 160,
        name: "Wiki Berry",
        description: "",
    },
    "magoberry" => ItemData {
        num: 161,
        name: "Mago Berry",
        description: "",
    },
    "aguavberry" => ItemData {
        num: 162,
        name: "Aguav Berry",
        description: "",
    },
    "iapapaberry" => ItemData {
        num: 163,
        name: "Iapapa Berry",
        description: "",
    },
    "razzberry" => ItemData {
        num: 164,
        name: "Razz Berry",
        description: "",
    },
    "blukberry" => ItemData {
        num: 165,
        name: "Bluk Berry",
        description: "",
    },
    "nanabberry" => ItemData {
        num: 166,
        name: "Nanab Berry",
        description: "",
    },
    "wepearberry" => ItemData {
        num: 167,
        name: "Wepear Berry",
        description: "",
    },
    "pinapberry" => ItemData {
        num: 168,
        name: "Pinap Berry",
        description: "",
    },
    "pomegberry" => ItemData {
        num: 169,
        name: "Pomeg Berry",
        description: "",
    },
    "kelpsyberry" => ItemData {
        num: 170,
        name: "Kelpsy Berry",
        description: "",
    },
    "qualotberry" => ItemData {
        num: 171,
        name: "Qualot Berry",
        description: "",
    },
    "hondewberry" => ItemData {
        num: 172,
        name: "Hondew Berry",
        description: "",
    },
    "grepaberry" => ItemData {
        num: 173,
        name: "Grepa Berry",
        description: "",
    },
    "tamatoberry" => ItemData {
        num: 174,
        name: "Tamato Berry",
        description: "",
    },
    "cornnberry" => ItemData {
        num: 175,
        name: "Cornn Berry",
        description: "",
    },
    "magostberry" => ItemData {
        num: 176,
        name: "Magost Berry",
        description: "",
    },
    "rabutaberry" => ItemData {
        num: 177,
        name: "Rabuta Berry",
        description: "",
    },
    "nomelberry" => ItemData {
        num: 178,
        name: "Nomel Berry",
        description: "",
    },
    "spelonberry" => ItemData {
        num: 179,
        name: "Spelon Berry",
        description: "",
    },
    "pamtreberry" => ItemData {
        num: 180,
        name: "Pamtre Berry",
        description: "",
    },
    "watmelberry" => ItemData {
        num: 181,
        name: "Watmel Berry",
        description: "",
    },
    "durinberry" => ItemData {
        num: 182,
        name: "Durin Berry",
        description: "",
    },
    "belueberry" => ItemData {
        num: 183,
        name: "Belue Berry",
        description: "",
    },
    "occaberry" => ItemData {
        num: 184,
        name: "Occa Berry",
        description: "",
    },
    "passhoberry" => ItemData {
        num: 185,
        name: "Passho Berry",
        description: "",
    },
    "wacanberry" => ItemData {
        num: 186,
        name: "Wacan Berry",
        description: "",
    },
    "rindoberry" => ItemData {
        num: 187,
        name: "Rindo Berry",
        description: "",
    },
    "yacheberry" => ItemData {
        num: 188,
        name: "Yache Berry",
        description: "",
    },
    "chopleberry" => ItemData {
        num: 189,
        name: "Chople Berry",
        description: "",
    },
    "kebiaberry" => ItemData {
        num: 190,
        name: "Kebia Berry",
        description: "",
    },
    "shucaberry" => ItemData {
        num: 191,
        name: "Shuca Berry",
        description: "",
    },
    "cobaberry" => ItemData {
        num: 192,
        name: "Coba Berry",
        description: "",
    },
    "payapaberry" => ItemData {
        num: 193,
        name: "Payapa Berry",
        description: "",
    },
    "tangaberry" => ItemData {
        num: 194,
        name: "Tanga Berry",
        description: "",
    },
    "chartiberry" => ItemData {
        num: 195,
        name: "Charti Berry",
        description: "",
    },
    "kasibberry" => ItemData {
        num: 196,
        name: "Kasib Berry",
        description: "",
    },
    "habanberry" => ItemData {
        num: 197,
        name: "Haban Berry",
        description: "",
    },
    "colburberry" => ItemData {
        num: 198,
        name: "Colbur Berry",
        description: "",
    },
    "babiriberry" => ItemData {
        num: 199,
        name: "Babiri Berry",
        description: "",
    },
    "chilanberry" => ItemData {
        num: 200,
        name: "Chilan Berry",
        description: "",
    },
    "liechiberry" => ItemData {
        num: 201,
        name: "Liechi Berry",
        description: "",
    },
    "ganlonberry" => ItemData {
        num: 202,
        name: "Ganlon Berry",
        description: "",
    },
    "salacberry" => ItemData {
        num: 203,
        name: "Salac Berry",
        description: "",
    },
    "petayaberry" => ItemData {
        num: 204,
        name: "Petaya Berry",
        description: "",
    },
    "apicotberry" => ItemData {
        num: 205,
        name: "Apicot Berry",
        description: "",
    },
    "lansatberry" => ItemData {
        num: 206,
        name: "Lansat Berry",
        description: "",
    },
    "starfberry" => ItemData {
        num: 207,
        name: "Starf Berry",
        description: "",
    },
    "enigmaberry" => ItemData {
        num: 208,
        name: "Enigma Berry",
        description: "",
    },
    "micleberry" => ItemData {
        num: 209,
        name: "Micle Berry",
        description: "",
    },
    "custapberry" => ItemData {
        num: 210,
        name: "Custap Berry",
        description: "",
    },
    "jabocaberry" => ItemData {
        num: 211,
        name: "Jaboca Berry",
        description: "",
    },
    "rowapberry" => ItemData {
        num: 212,
        name: "Rowap Berry",
        description: "",
    },
    "brightpowder" => ItemData {
        num: 213,
        name: "Bright Powder",
        description: "",
    },
    "whiteherb" => ItemData {
        num: 214,
        name: "White Herb",
        description: "",
    },
    "machobrace" => ItemData {
        num: 215,
        name: "Macho Brace",
        description: "",
    },
    "quickclaw" => ItemData {
        num: 217,
        name: "Quick Claw",
        description: "",
    },
    "mentalherb" => ItemData {
        num: 219,
        name: "Mental Herb",
        description: "",
    },
    "choiceband" => ItemData {
        num: 220,
        name: "Choice Band",
        description: "",
    },
    "kingsrock" => ItemData {
        num: 221,
        name: "King's Rock",
        description: "",
    },
    "silverpowder" => ItemData {
        num: 222,
        name: "Silver Powder",
        description: "",
    },
    "souldew" => ItemData {
        num: 225,
        name: "Soul Dew",
        description: "",
    },
    "deepseatooth" => ItemData {
        num: 226,
        name: "Deep Sea Tooth",
        description: "",
    },
    "deepseascale" => ItemData {
        num: 227,
        name: "Deep Sea Scale",
        description: "",
    },
    "focusband" => ItemData {
        num: 230,
        name: "Focus Band",
        description: "",
    },
    "scopelens" => ItemData {
        num: 232,
        name: "Scope Lens",
        description: "",
    },
    "metalcoat" => ItemData {
        num: 233,
        name: "Metal Coat",
        description: "",
    },
    "leftovers" => ItemData {
        num: 234,
        name: "Leftovers",
        description: "",
    },
    "dragonscale" => ItemData {
        num: 235,
        name: "Dragon Scale",
        description: "",
    },
    "lightball" => ItemData {
        num: 236,
        name: "Light Ball",
        description: "",
    },
    "softsand" => ItemData {
        num: 237,
        name: "Soft Sand",
        description: "",
    },
    "hardstone" => ItemData {
        num: 238,
        name: "Hard Stone",
        description: "",
    },
    "miracleseed" => ItemData {
        num: 239,
        name: "Miracle Seed",
        description: "",
    },
    "blackglasses" => ItemData {
        num: 240,
        name: "Black Glasses",
        description: "",
    },
    "blackbelt" => ItemData {
        num: 241,
        name: "Black Belt",
        description: "",
    },
    "magnet" => ItemData {
        num: 242,
        name: "Magnet",
        description: "",
    },
    "mysticwater" => ItemData {
        num: 243,
        name: "Mystic Water",
        description: "",
    },
    "sharpbeak" => ItemData {
        num: 244,
        name: "Sharp Beak",
        description: "",
    },
    "poisonbarb" => ItemData {
        num: 245,
        name: "Poison Barb",
        description: "",
    },
    "nevermeltice" => ItemData {
        num: 246,
        name: "Never-Melt Ice",
        description: "",
    },
    "spelltag" => ItemData {
        num: 247,
        name: "Spell Tag",
        description: "",
    },
    "twistedspoon" => ItemData {
        num: 248,
        name: "Twisted Spoon",
        description: "",
    },
    "charcoal" => ItemData {
        num: 249,
        name: "Charcoal",
        description: "",
    },
    "dragonfang" => ItemData {
        num: 250,
        name: "Dragon Fang",
        description: "",
    },
    "pinkbow" => ItemData {
        num: 251,
        name: "Pink Bow",
        description: "",
    },
    "polkadotbow" => ItemData {
        num: 251,
        name: "Polkadot Bow",
        description: "",
    },
    "silkscarf" => ItemData {
        num: 251,
        name: "Silk Scarf",
        description: "",
    },
    "upgrade" => ItemData {
        num: 252,
        name: "Up-Grade",
        description: "",
    },
    "shellbell" => ItemData {
        num: 253,
        name: "Shell Bell",
        description: "",
    },
    "seaincense" => ItemData {
        num: 254,
        name: "Sea Incense",
        description: "",
    },
    "laxincense" => ItemData {
        num: 255,
        name: "Lax Incense",
        description: "",
    },
    "luckypunch" => ItemData {
        num: 256,
        name: "Lucky Punch",
        description: "",
    },
    "metalpowder" => ItemData {
        num: 257,
        name: "Metal Powder",
        description: "",
    },
    "thickclub" => ItemData {
        num: 258,
        name: "Thick Club",
        description: "",
    },
    "leek" => ItemData {
        num: 259,
        name: "Leek",
        description: "",
    },
    "stick" => ItemData {
        num: 259,
        name: "Stick",
        description: "",
    },
    "widelens" => ItemData {
        num: 265,
        name: "Wide Lens",
        description: "",
    },
    "muscleband" => ItemData {
        num: 266,
        name: "Muscle Band",
        description: "",
    },
    "wiseglasses" => ItemData {
        num: 267,
        name: "Wise Glasses",
        description: "",
    },
    "expertbelt" => ItemData {
        num: 268,
        name: "Expert Belt",
        description: "",
    },
    "lightclay" => ItemData {
        num: 269,
        name: "Light Clay",
        description: "",
    },
    "lifeorb" => ItemData {
        num: 270,
        name: "Life Orb",
        description: "",
    },
    "powerherb" => ItemData {
        num: 271,
        name: "Power Herb",
        description: "",
    },
    "toxicorb" => ItemData {
        num: 272,
        name: "Toxic Orb",
        description: "",
    },
    "flameorb" => ItemData {
        num: 273,
        name: "Flame Orb",
        description: "",
    },
    "quickpowder" => ItemData {
        num: 274,
        name: "Quick Powder",
        description: "",
    },
    "focussash" => ItemData {
        num: 275,
        name: "Focus Sash",
        description: "",
    },
    "zoomlens" => ItemData {
        num: 276,
        name: "Zoom Lens",
        description: "",
    },
    "metronome" => ItemData {
        num: 277,
        name: "Metronome",
        description: "",
    },
    "ironball" => ItemData {
        num: 278,
        name: "Iron Ball",
        description: "",
    },
    "laggingtail" => ItemData {
        num: 279,
        name: "Lagging Tail",
        description: "",
    },
    "destinyknot" => ItemData {
        num: 280,
        name: "Destiny Knot",
        description: "",
    },
    "blacksludge" => ItemData {
        num: 281,
        name: "Black Sludge",
        description: "",
    },
    "icyrock" => ItemData {
        num: 282,
        name: "Icy Rock",
        description: "",
    },
    "smoothrock" => ItemData {
        num: 283,
        name: "Smooth Rock",
        description: "",
    },
    "heatrock" => ItemData {
        num: 284,
        name: "Heat Rock",
        description: "",
    },
    "damprock" => ItemData {
        num: 285,
        name: "Damp Rock",
        description: "",
    },
    "gripclaw" => ItemData {
        num: 286,
        name: "Grip Claw",
        description: "",
    },
    "choicescarf" => ItemData {
        num: 287,
        name: "Choice Scarf",
        description: "",
    },
    "stickybarb" => ItemData {
        num: 288,
        name: "Sticky Barb",
        description: "",
    },
    "powerbracer" => ItemData {
        num: 289,
        name: "Power Bracer",
        description: "",
    },
    "powerbelt" => ItemData {
        num: 290,
        name: "Power Belt",
        description: "",
    },
    "powerlens" => ItemData {
        num: 291,
        name: "Power Lens",
        description: "",
    },
    "powerband" => ItemData {
        num: 292,
        name: "Power Band",
        description: "",
    },
    "poweranklet" => ItemData {
        num: 293,
        name: "Power Anklet",
        description: "",
    },
    "powerweight" => ItemData {
        num: 294,
        name: "Power Weight",
        description: "",
    },
    "shedshell" => ItemData {
        num: 295,
        name: "Shed Shell",
        description: "",
    },
    "bigroot" => ItemData {
        num: 296,
        name: "Big Root",
        description: "",
    },
    "choicespecs" => ItemData {
        num: 297,
        name: "Choice Specs",
        description: "",
    },
    "flameplate" => ItemData {
        num: 298,
        name: "Flame Plate",
        description: "",
    },
    "splashplate" => ItemData {
        num: 299,
        name: "Splash Plate",
        description: "",
    },
    "zapplate" => ItemData {
        num: 300,
        name: "Zap Plate",
        description: "",
    },
    "meadowplate" => ItemData {
        num: 301,
        name: "Meadow Plate",
        description: "",
    },
    "icicleplate" => ItemData {
        num: 302,
        name: "Icicle Plate",
        description: "",
    },
    "fistplate" => ItemData {
        num: 303,
        name: "Fist Plate",
        description: "",
    },
    "toxicplate" => ItemData {
        num: 304,
        name: "Toxic Plate",
        description: "",
    },
    "earthplate" => ItemData {
        num: 305,
        name: "Earth Plate",
        description: "",
    },
    "skyplate" => ItemData {
        num: 306,
        name: "Sky Plate",
        description: "",
    },
    "mindplate" => ItemData {
        num: 307,
        name: "Mind Plate",
        description: "",
    },
    "insectplate" => ItemData {
        num: 308,
        name: "Insect Plate",
        description: "",
    },
    "stoneplate" => ItemData {
        num: 309,
        name: "Stone Plate",
        description: "",
    },
    "spookyplate" => ItemData {
        num: 310,
        name: "Spooky Plate",
        description: "",
    },
    "dracoplate" => ItemData {
        num: 311,
        name: "Draco Plate",
        description: "",
    },
    "dreadplate" => ItemData {
        num: 312,
        name: "Dread Plate",
        description: "",
    },
    "ironplate" => ItemData {
        num: 313,
        name: "Iron Plate",
        description: "",
    },
    "oddincense" => ItemData {
        num: 314,
        name: "Odd Incense",
        description: "",
    },
    "rockincense" => ItemData {
        num: 315,
        name: "Rock Incense",
        description: "",
    },
    "fullincense" => ItemData {
        num: 316,
        name: "Full Incense",
        description: "",
    },
    "waveincense" => ItemData {
        num: 317,
        name: "Wave Incense",
        description: "",
    },
    "roseincense" => ItemData {
        num: 318,
        name: "Rose Incense",
        description: "",
    },
    "protector" => ItemData {
        num: 321,
        name: "Protector",
        description: "",
    },
    "electirizer" => ItemData {
        num: 322,
        name: "Electirizer",
        description: "",
    },
    "magmarizer" => ItemData {
        num: 323,
        name: "Magmarizer",
        description: "",
    },
    "dubiousdisc" => ItemData {
        num: 324,
        name: "Dubious Disc",
        description: "",
    },
    "reapercloth" => ItemData {
        num: 325,
        name: "Reaper Cloth",
        description: "",
    },
    "razorclaw" => ItemData {
        num: 326,
        name: "Razor Claw",
        description: "",
    },
    "razorfang" => ItemData {
        num: 327,
        name: "Razor Fang",
        description: "",
    },
    "fastball" => ItemData {
        num: 492,
        name: "Fast Ball",
        description: "",
    },
    "levelball" => ItemData {
        num: 493,
        name: "Level Ball",
        description: "",
    },
    "lureball" => ItemData {
        num: 494,
        name: "Lure Ball",
        description: "",
    },
    "heavyball" => ItemData {
        num: 495,
        name: "Heavy Ball",
        description: "",
    },
    "loveball" => ItemData {
        num: 496,
        name: "Love Ball",
        description: "",
    },
    "friendball" => ItemData {
        num: 497,
        name: "Friend Ball",
        description: "",
    },
    "moonball" => ItemData {
        num: 498,
        name: "Moon Ball",
        description: "",
    },
    "sportball" => ItemData {
        num: 499,
        name: "Sport Ball",
        description: "",
    },
    "parkball" => ItemData {
        num: 500,
        name: "Park Ball",
        description: "",
    },
    "redorb" => ItemData {
        num: 534,
        name: "Red Orb",
        description: "",
    },
    "blueorb" => ItemData {
        num: 535,
        name: "Blue Orb",
        description: "",
    },
    "prismscale" => ItemData {
        num: 537,
        name: "Prism Scale",
        description: "",
    },
    "eviolite" => ItemData {
        num: 538,
        name: "Eviolite",
        description: "",
    },
    "floatstone" => ItemData {
        num: 539,
        name: "Float Stone",
        description: "",
    },
    "rockyhelmet" => ItemData {
        num: 540,
        name: "Rocky Helmet",
        description: "",
    },
    "airballoon" => ItemData {
        num: 541,
        name: "Air Balloon",
        description: "",
    },
    "redcard" => ItemData {
        num: 542,
        name: "Red Card",
        description: "",
    },
    "ringtarget" => ItemData {
        num: 543,
        name: "Ring Target",
        description: "",
    },
    "bindingband" => ItemData {
        num: 544,
        name: "Binding Band",
        description: "",
    },
    "absorbbulb" => ItemData {
        num: 545,
        name: "Absorb Bulb",
        description: "",
    },
    "cellbattery" => ItemData {
        num: 546,
        name: "Cell Battery",
        description: "",
    },
    "ejectbutton" => ItemData {
        num: 547,
        name: "Eject Button",
        description: "",
    },
    "firegem" => ItemData {
        num: 548,
        name: "Fire Gem",
        description: "",
    },
    "watergem" => ItemData {
        num: 549,
        name: "Water Gem",
        description: "",
    },
    "electricgem" => ItemData {
        num: 550,
        name: "Electric Gem",
        description: "",
    },
    "grassgem" => ItemData {
        num: 551,
        name: "Grass Gem",
        description: "",
    },
    "icegem" => ItemData {
        num: 552,
        name: "Ice Gem",
        description: "",
    },
    "fightinggem" => ItemData {
        num: 553,
        name: "Fighting Gem",
        description: "",
    },
    "poisongem" => ItemData {
        num: 554,
        name: "Poison Gem",
        description: "",
    },
    "groundgem" => ItemData {
        num: 555,
        name: "Ground Gem",
        description: "",
    },
    "flyinggem" => ItemData {
        num: 556,
        name: "Flying Gem",
        description: "",
    },
    "psychicgem" => ItemData {
        num: 557,
        name: "Psychic Gem",
        description: "",
    },
    "buggem" => ItemData {
        num: 558,
        name: "Bug Gem",
        description: "",
    },
    "rockgem" => ItemData {
        num: 559,
        name: "Rock Gem",
        description: "",
    },
    "ghostgem" => ItemData {
        num: 560,
        name: "Ghost Gem",
        description: "",
    },
    "dragongem" => ItemData {
        num: 561,
        name: "Dragon Gem",
        description: "",
    },
    "darkgem" => ItemData {
        num: 562,
        name: "Dark Gem",
        description: "",
    },
    "steelgem" => ItemData {
        num: 563,
        name: "Steel Gem",
        description: "",
    },
    "normalgem" => ItemData {
        num: 564,
        name: "Normal Gem",
        description: "",
    },
    "prettyfeather" => ItemData {
        num: 571,
        name: "Pretty Feather",
        description: "",
    },
    "coverfossil" => ItemData {
        num: 572,
        name: "Cover Fossil",
        description: "",
    },
    "plumefossil" => ItemData {
        num: 573,
        name: "Plume Fossil",
        description: "",
    },
    "dreamball" => ItemData {
        num: 576,
        name: "Dream Ball",
        description: "",
    },
    "bignugget" => ItemData {
        num: 581,
        name: "Big Nugget",
        description: "",
    },
    "weaknesspolicy" => ItemData {
        num: 639,
        name: "Weakness Policy",
        description: "",
    },
    "assaultvest" => ItemData {
        num: 640,
        name: "Assault Vest",
        description: "",
    },
    "pixieplate" => ItemData {
        num: 644,
        name: "Pixie Plate",
        description: "",
    },
    "whippeddream" => ItemData {
        num: 646,
        name: "Whipped Dream",
        description: "",
    },
    "sachet" => ItemData {
        num: 647,
        name: "Sachet",
        description: "",
    },
    "luminousmoss" => ItemData {
        num: 648,
        name: "Luminous Moss",
        description: "",
    },
    "snowball" => ItemData {
        num: 649,
        name: "Snowball",
        description: "",
    },
    "safetygoggles" => ItemData {
        num: 650,
        name: "Safety Goggles",
        description: "",
    },
    "gengarite" => ItemData {
        num: 656,
        name: "Gengarite",
        description: "",
    },
    "gardevoirite" => ItemData {
        num: 657,
        name: "Gardevoirite",
        description: "",
    },
    "ampharosite" => ItemData {
        num: 658,
        name: "Ampharosite",
        description: "",
    },
    "venusaurite" => ItemData {
        num: 659,
        name: "Venusaurite",
        description: "",
    },
    "charizarditex" => ItemData {
        num: 660,
        name: "Charizardite X",
        description: "",
    },
    "blastoisinite" => ItemData {
        num: 661,
        name: "Blastoisinite",
        description: "",
    },
    "mewtwonitex" => ItemData {
        num: 662,
        name: "Mewtwonite X",
        description: "",
    },
    "mewtwonitey" => ItemData {
        num: 663,
        name: "Mewtwonite Y",
        description: "",
    },
    "blazikenite" => ItemData {
        num: 664,
        name: "Blazikenite",
        description: "",
    },
    "medichamite" => ItemData {
        num: 665,
        name: "Medichamite",
        description: "",
    },
    "houndoominite" => ItemData {
        num: 666,
        name: "Houndoominite",
        description: "",
    },
    "aggronite" => ItemData {
        num: 667,
        name: "Aggronite",
        description: "",
    },
    "banettite" => ItemData {
        num: 668,
        name: "Banettite",
        description: "",
    },
    "tyranitarite" => ItemData {
        num: 669,
        name: "Tyranitarite",
        description: "",
    },
    "scizorite" => ItemData {
        num: 670,
        name: "Scizorite",
        description: "",
    },
    "pinsirite" => ItemData {
        num: 671,
        name: "Pinsirite",
        description: "",
    },
    "aerodactylite" => ItemData {
        num: 672,
        name: "Aerodactylite",
        description: "",
    },
    "lucarionite" => ItemData {
        num: 673,
        name: "Lucarionite",
        description: "",
    },
    "abomasite" => ItemData {
        num: 674,
        name: "Abomasite",
        description: "",
    },
    "kangaskhanite" => ItemData {
        num: 675,
        name: "Kangaskhanite",
        description: "",
    },
    "gyaradosite" => ItemData {
        num: 676,
        name: "Gyaradosite",
        description: "",
    },
    "absolite" => ItemData {
        num: 677,
        name: "Absolite",
        description: "",
    },
    "charizarditey" => ItemData {
        num: 678,
        name: "Charizardite Y",
        description: "",
    },
    "alakazite" => ItemData {
        num: 679,
        name: "Alakazite",
        description: "",
    },
    "heracronite" => ItemData {
        num: 680,
        name: "Heracronite",
        description: "",
    },
    "mawilite" => ItemData {
        num: 681,
        name: "Mawilite",
        description: "",
    },
    "manectite" => ItemData {
        num: 682,
        name: "Manectite",
        description: "",
    },
    "garchompite" => ItemData {
        num: 683,
        name: "Garchompite",
        description: "",
    },
    "latiasite" => ItemData {
        num: 684,
        name: "Latiasite",
        description: "",
    },
    "latiosite" => ItemData {
        num: 685,
        name: "Latiosite",
        description: "",
    },
    "roseliberry" => ItemData {
        num: 686,
        name: "Roseli Berry",
        description: "",
    },
    "keeberry" => ItemData {
        num: 687,
        name: "Kee Berry",
        description: "",
    },
    "marangaberry" => ItemData {
        num: 688,
        name: "Maranga Berry",
        description: "",
    },
    "jawfossil" => ItemData {
        num: 710,
        name: "Jaw Fossil",
        description: "",
    },
    "sailfossil" => ItemData {
        num: 711,
        name: "Sail Fossil",
        description: "",
    },
    "fairygem" => ItemData {
        num: 715,
        name: "Fairy Gem",
        description: "",
    },
    "swampertite" => ItemData {
        num: 752,
        name: "Swampertite",
        description: "",
    },
    "sceptilite" => ItemData {
        num: 753,
        name: "Sceptilite",
        description: "",
    },
    "sablenite" => ItemData {
        num: 754,
        name: "Sablenite",
        description: "",
    },
    "altarianite" => ItemData {
        num: 755,
        name: "Altarianite",
        description: "",
    },
    "galladite" => ItemData {
        num: 756,
        name: "Galladite",
        description: "",
    },
    "audinite" => ItemData {
        num: 757,
        name: "Audinite",
        description: "",
    },
    "metagrossite" => ItemData {
        num: 758,
        name: "Metagrossite",
        description: "",
    },
    "sharpedonite" => ItemData {
        num: 759,
        name: "Sharpedonite",
        description: "",
    },
    "slowbronite" => ItemData {
        num: 760,
        name: "Slowbronite",
        description: "",
    },
    "steelixite" => ItemData {
        num: 761,
        name: "Steelixite",
        description: "",
    },
    "pidgeotite" => ItemData {
        num: 762,
        name: "Pidgeotite",
        description: "",
    },
    "glalitite" => ItemData {
        num: 763,
        name: "Glalitite",
        description: "",
    },
    "diancite" => ItemData {
        num: 764,
        name: "Diancite",
        description: "",
    },
    "cameruptite" => ItemData {
        num: 767,
        name: "Cameruptite",
        description: "",
    },
    "lopunnite" => ItemData {
        num: 768,
        name: "Lopunnite",
        description: "",
    },
    "salamencite" => ItemData {
        num: 769,
        name: "Salamencite",
        description: "",
    },
    "beedrillite" => ItemData {
        num: 770,
        name: "Beedrillite",
        description: "",
    },
    "normaliumz" => ItemData {
        num: 776,
        name: "Normalium Z",
        description: "",
    },
    "firiumz" => ItemData {
        num: 777,
        name: "Firium Z",
        description: "",
    },
    "wateriumz" => ItemData {
        num: 778,
        name: "Waterium Z",
        description: "",
    },
    "electriumz" => ItemData {
        num: 779,
        name: "Electrium Z",
        description: "",
    },
    "grassiumz" => ItemData {
        num: 780,
        name: "Grassium Z",
        description: "",
    },
    "iciumz" => ItemData {
        num: 781,
        name: "Icium Z",
        description: "",
    },
    "fightiniumz" => ItemData {
        num: 782,
        name: "Fightinium Z",
        description: "",
    },
    "poisoniumz" => ItemData {
        num: 783,
        name: "Poisonium Z",
        description: "",
    },
    "groundiumz" => ItemData {
        num: 784,
        name: "Groundium Z",
        description: "",
    },
    "flyiniumz" => ItemData {
        num: 785,
        name: "Flyinium Z",
        description: "",
    },
    "psychiumz" => ItemData {
        num: 786,
        name: "Psychium Z",
        description: "",
    },
    "buginiumz" => ItemData {
        num: 787,
        name: "Buginium Z",
        description: "",
    },
    "rockiumz" => ItemData {
        num: 788,
        name: "Rockium Z",
        description: "",
    },
    "ghostiumz" => ItemData {
        num: 789,
        name: "Ghostium Z",
        description: "",
    },
    "dragoniumz" => ItemData {
        num: 790,
        name: "Dragonium Z",
        description: "",
    },
    "darkiniumz" => ItemData {
        num: 791,
        name: "Darkinium Z",
        description: "",
    },
    "steeliumz" => ItemData {
        num: 792,
        name: "Steelium Z",
        description: "",
    },
    "fairiumz" => ItemData {
        num: 793,
        name: "Fairium Z",
        description: "",
    },
    "pikaniumz" => ItemData {
        num: 794,
        name: "Pikanium Z",
        description: "",
    },
    "bottlecap" => ItemData {
        num: 795,
        name: "Bottle Cap",
        description: "",
    },
    "goldbottlecap" => ItemData {
        num: 796,
        name: "Gold Bottle Cap",
        description: "",
    },
    "decidiumz" => ItemData {
        num: 798,
        name: "Decidium Z",
        description: "",
    },
    "inciniumz" => ItemData {
        num: 799,
        name: "Incinium Z",
        description: "",
    },
    "primariumz" => ItemData {
        num: 800,
        name: "Primarium Z",
        description: "",
    },
    "tapuniumz" => ItemData {
        num: 801,
        name: "Tapunium Z",
        description: "",
    },
    "marshadiumz" => ItemData {
        num: 802,
        name: "Marshadium Z",
        description: "",
    },
    "aloraichiumz" => ItemData {
        num: 803,
        name: "Aloraichium Z",
        description: "",
    },
    "snorliumz" => ItemData {
        num: 804,
        name: "Snorlium Z",
        description: "",
    },
    "eeviumz" => ItemData {
        num: 805,
        name: "Eevium Z",
        description: "",
    },
    "mewniumz" => ItemData {
        num: 806,
        name: "Mewnium Z",
        description: "",
    },
    "pikashuniumz" => ItemData {
        num: 836,
        name: "Pikashunium Z",
        description: "",
    },
    "adrenalineorb" => ItemData {
        num: 846,
        name: "Adrenaline Orb",
        description: "",
    },
    "icestone" => ItemData {
        num: 849,
        name: "Ice Stone",
        description: "",
    },
    "beastball" => ItemData {
        num: 851,
        name: "Beast Ball",
        description: "",
    },
    "terrainextender" => ItemData {
        num: 879,
        name: "Terrain Extender",
        description: "",
    },
    "protectivepads" => ItemData {
        num: 880,
        name: "Protective Pads",
        description: "",
    },
    "electricseed" => ItemData {
        num: 881,
        name: "Electric Seed",
        description: "",
    },
    "psychicseed" => ItemData {
        num: 882,
        name: "Psychic Seed",
        description: "",
    },
    "mistyseed" => ItemData {
        num: 883,
        name: "Misty Seed",
        description: "",
    },
    "grassyseed" => ItemData {
        num: 884,
        name: "Grassy Seed",
        description: "",
    },
    "fightingmemory" => ItemData {
        num: 904,
        name: "Fighting Memory",
        description: "",
    },
    "flyingmemory" => ItemData {
        num: 905,
        name: "Flying Memory",
        description: "",
    },
    "poisonmemory" => ItemData {
        num: 906,
        name: "Poison Memory",
        description: "",
    },
    "groundmemory" => ItemData {
        num: 907,
        name: "Ground Memory",
        description: "",
    },
    "rockmemory" => ItemData {
        num: 908,
        name: "Rock Memory",
        description: "",
    },
    "bugmemory" => ItemData {
        num: 909,
        name: "Bug Memory",
        description: "",
    },
    "ghostmemory" => ItemData {
        num: 910,
        name: "Ghost Memory",
        description: "",
    },
    "steelmemory" => ItemData {
        num: 911,
        name: "Steel Memory",
        description: "",
    },
    "firememory" => ItemData {
        num: 912,
        name: "Fire Memory",
        description: "",
    },
    "watermemory" => ItemData {
        num: 913,
        name: "Water Memory",
        description: "",
    },
    "grassmemory" => ItemData {
        num: 914,
        name: "Grass Memory",
        description: "",
    },
    "electricmemory" => ItemData {
        num: 915,
        name: "Electric Memory",
        description: "",
    },
    "psychicmemory" => ItemData {
        num: 916,
        name: "Psychic Memory",
        description: "",
    },
    "icememory" => ItemData {
        num: 917,
        name: "Ice Memory",
        description: "",
    },
    "dragonmemory" => ItemData {
        num: 918,
        name: "Dragon Memory",
        description: "",
    },
    "darkmemory" => ItemData {
        num: 919,
        name: "Dark Memory",
        description: "",
    },
    "fairymemory" => ItemData {
        num: 920,
        name: "Fairy Memory",
        description: "",
    },
    "solganiumz" => ItemData {
        num: 921,
        name: "Solganium Z",
        description: "",
    },
    "lunaliumz" => ItemData {
        num: 922,
        name: "Lunalium Z",
        description: "",
    },
    "ultranecroziumz" => ItemData {
        num: 923,
        name: "Ultranecrozium Z",
        description: "",
    },
    "mimikiumz" => ItemData {
        num: 924,
        name: "Mimikium Z",
        description: "",
    },
    "lycaniumz" => ItemData {
        num: 925,
        name: "Lycanium Z",
        description: "",
    },
    "kommoniumz" => ItemData {
        num: 926,
        name: "Kommonium Z",
        description: "",
    },
    "rustedsword" => ItemData {
        num: 1103,
        name: "Rusted Sword",
        description: "",
    },
    "rustedshield" => ItemData {
        num: 1104,
        name: "Rusted Shield",
        description: "",
    },
    "fossilizedbird" => ItemData {
        num: 1105,
        name: "Fossilized Bird",
        description: "",
    },
    "fossilizedfish" => ItemData {
        num: 1106,
        name: "Fossilized Fish",
        description: "",
    },
    "fossilizeddrake" => ItemData {
        num: 1107,
        name: "Fossilized Drake",
        description: "",
    },
    "fossilizeddino" => ItemData {
        num: 1108,
        name: "Fossilized Dino",
        description: "",
    },
    "strawberrysweet" => ItemData {
        num: 1109,
        name: "Strawberry Sweet",
        description: "",
    },
    "lovesweet" => ItemData {
        num: 1110,
        name: "Love Sweet",
        description: "",
    },
    "berrysweet" => ItemData {
        num: 1111,
        name: "Berry Sweet",
        description: "",
    },
    "cloversweet" => ItemData {
        num: 1112,
        name: "Clover Sweet",
        description: "",
    },
    "flowersweet" => ItemData {
        num: 1113,
        name: "Flower Sweet",
        description: "",
    },
    "starsweet" => ItemData {
        num: 1114,
        name: "Star Sweet",
        description: "",
    },
    "ribbonsweet" => ItemData {
        num: 1115,
        name: "Ribbon Sweet",
        description: "",
    },
    "sweetapple" => ItemData {
        num: 1116,
        name: "Sweet Apple",
        description: "",
    },
    "tartapple" => ItemData {
        num: 1117,
        name: "Tart Apple",
        description: "",
    },
    "throatspray" => ItemData {
        num: 1118,
        name: "Throat Spray",
        description: "",
    },
    "ejectpack" => ItemData {
        num: 1119,
        name: "Eject Pack",
        description: "",
    },
    "heavydutyboots" => ItemData {
        num: 1120,
        name: "Heavy-Duty Boots",
        description: "",
    },
    "blunderpolicy" => ItemData {
        num: 1121,
        name: "Blunder Policy",
        description: "",
    },
    "roomservice" => ItemData {
        num: 1122,
        name: "Room Service",
        description: "",
    },
    "utilityumbrella" => ItemData {
        num: 1123,
        name: "Utility Umbrella",
        description: "",
    },
    "tr00" => ItemData {
        num: 1130,
        name: "TR00",
        description: "",
    },
    "tr01" => ItemData {
        num: 1131,
        name: "TR01",
        description: "",
    },
    "tr02" => ItemData {
        num: 1132,
        name: "TR02",
        description: "",
    },
    "tr03" => ItemData {
        num: 1133,
        name: "TR03",
        description: "",
    },
    "tr04" => ItemData {
        num: 1134,
        name: "TR04",
        description: "",
    },
    "tr05" => ItemData {
        num: 1135,
        name: "TR05",
        description: "",
    },
    "tr06" => ItemData {
        num: 1136,
        name: "TR06",
        description: "",
    },
    "tr07" => ItemData {
        num: 1137,
        name: "TR07",
        description: "",
    },
    "tr08" => ItemData {
        num: 1138,
        name: "TR08",
        description: "",
    },
    "tr09" => ItemData {
        num: 1139,
        name: "TR09",
        description: "",
    },
    "tr10" => ItemData {
        num: 1140,
        name: "TR10",
        description: "",
    },
    "tr11" => ItemData {
        num: 1141,
        name: "TR11",
        description: "",
    },
    "tr12" => ItemData {
        num: 1142,
        name: "TR12",
        description: "",
    },
    "tr13" => ItemData {
        num: 1143,
        name: "TR13",
        description: "",
    },
    "tr14" => ItemData {
        num: 1144,
        name: "TR14",
        description: "",
    },
    "tr15" => ItemData {
        num: 1145,
        name: "TR15",
        description: "",
    },
    "tr16" => ItemData {
        num: 1146,
        name: "TR16",
        description: "",
    },
    "tr17" => ItemData {
        num: 1147,
        name: "TR17",
        description: "",
    },
    "tr18" => ItemData {
        num: 1148,
        name: "TR18",
        description: "",
    },
    "tr19" => ItemData {
        num: 1149,
        name: "TR19",
        description: "",
    },
    "tr20" => ItemData {
        num: 1150,
        name: "TR20",
        description: "",
    },
    "tr21" => ItemData {
        num: 1151,
        name: "TR21",
        description: "",
    },
    "tr22" => ItemData {
        num: 1152,
        name: "TR22",
        description: "",
    },
    "tr23" => ItemData {
        num: 1153,
        name: "TR23",
        description: "",
    },
    "tr24" => ItemData {
        num: 1154,
        name: "TR24",
        description: "",
    },
    "tr25" => ItemData {
        num: 1155,
        name: "TR25",
        description: "",
    },
    "tr26" => ItemData {
        num: 1156,
        name: "TR26",
        description: "",
    },
    "tr27" => ItemData {
        num: 1157,
        name: "TR27",
        description: "",
    },
    "tr28" => ItemData {
        num: 1158,
        name: "TR28",
        description: "",
    },
    "tr29" => ItemData {
        num: 1159,
        name: "TR29",
        description: "",
    },
    "tr30" => ItemData {
        num: 1160,
        name: "TR30",
        description: "",
    },
    "tr31" => ItemData {
        num: 1161,
        name: "TR31",
        description: "",
    },
    "tr32" => ItemData {
        num: 1162,
        name: "TR32",
        description: "",
    },
    "tr33" => ItemData {
        num: 1163,
        name: "TR33",
        description: "",
    },
    "tr34" => ItemData {
        num: 1164,
        name: "TR34",
        description: "",
    },
    "tr35" => ItemData {
        num: 1165,
        name: "TR35",
        description: "",
    },
    "tr36" => ItemData {
        num: 1166,
        name: "TR36",
        description: "",
    },
    "tr37" => ItemData {
        num: 1167,
        name: "TR37",
        description: "",
    },
    "tr38" => ItemData {
        num: 1168,
        name: "TR38",
        description: "",
    },
    "tr39" => ItemData {
        num: 1169,
        name: "TR39",
        description: "",
    },
    "tr40" => ItemData {
        num: 1170,
        name: "TR40",
        description: "",
    },
    "tr41" => ItemData {
        num: 1171,
        name: "TR41",
        description: "",
    },
    "tr42" => ItemData {
        num: 1172,
        name: "TR42",
        description: "",
    },
    "tr43" => ItemData {
        num: 1173,
        name: "TR43",
        description: "",
    },
    "tr44" => ItemData {
        num: 1174,
        name: "TR44",
        description: "",
    },
    "tr45" => ItemData {
        num: 1175,
        name: "TR45",
        description: "",
    },
    "tr46" => ItemData {
        num: 1176,
        name: "TR46",
        description: "",
    },
    "tr47" => ItemData {
        num: 1177,
        name: "TR47",
        description: "",
    },
    "tr48" => ItemData {
        num: 1178,
        name: "TR48",
        description: "",
    },
    "tr49" => ItemData {
        num: 1179,
        name: "TR49",
        description: "",
    },
    "tr50" => ItemData {
        num: 1180,
        name: "TR50",
        description: "",
    },
    "tr51" => ItemData {
        num: 1181,
        name: "TR51",
        description: "",
    },
    "tr52" => ItemData {
        num: 1182,
        name: "TR52",
        description: "",
    },
    "tr53" => ItemData {
        num: 1183,
        name: "TR53",
        description: "",
    },
    "tr54" => ItemData {
        num: 1184,
        name: "TR54",
        description: "",
    },
    "tr55" => ItemData {
        num: 1185,
        name: "TR55",
        description: "",
    },
    "tr56" => ItemData {
        num: 1186,
        name: "TR56",
        description: "",
    },
    "tr57" => ItemData {
        num: 1187,
        name: "TR57",
        description: "",
    },
    "tr58" => ItemData {
        num: 1188,
        name: "TR58",
        description: "",
    },
    "tr59" => ItemData {
        num: 1189,
        name: "TR59",
        description: "",
    },
    "tr60" => ItemData {
        num: 1190,
        name: "TR60",
        description: "",
    },
    "tr61" => ItemData {
        num: 1191,
        name: "TR61",
        description: "",
    },
    "tr62" => ItemData {
        num: 1192,
        name: "TR62",
        description: "",
    },
    "tr63" => ItemData {
        num: 1193,
        name: "TR63",
        description: "",
    },
    "tr64" => ItemData {
        num: 1194,
        name: "TR64",
        description: "",
    },
    "tr65" => ItemData {
        num: 1195,
        name: "TR65",
        description: "",
    },
    "tr66" => ItemData {
        num: 1196,
        name: "TR66",
        description: "",
    },
    "tr67" => ItemData {
        num: 1197,
        name: "TR67",
        description: "",
    },
    "tr68" => ItemData {
        num: 1198,
        name: "TR68",
        description: "",
    },
    "tr69" => ItemData {
        num: 1199,
        name: "TR69",
        description: "",
    },
    "tr70" => ItemData {
        num: 1200,
        name: "TR70",
        description: "",
    },
    "tr71" => ItemData {
        num: 1201,
        name: "TR71",
        description: "",
    },
    "tr72" => ItemData {
        num: 1202,
        name: "TR72",
        description: "",
    },
    "tr73" => ItemData {
        num: 1203,
        name: "TR73",
        description: "",
    },
    "tr74" => ItemData {
        num: 1204,
        name: "TR74",
        description: "",
    },
    "tr75" => ItemData {
        num: 1205,
        name: "TR75",
        description: "",
    },
    "tr76" => ItemData {
        num: 1206,
        name: "TR76",
        description: "",
    },
    "tr77" => ItemData {
        num: 1207,
        name: "TR77",
        description: "",
    },
    "tr78" => ItemData {
        num: 1208,
        name: "TR78",
        description: "",
    },
    "tr79" => ItemData {
        num: 1209,
        name: "TR79",
        description: "",
    },
    "tr80" => ItemData {
        num: 1210,
        name: "TR80",
        description: "",
    },
    "tr81" => ItemData {
        num: 1211,
        name: "TR81",
        description: "",
    },
    "tr82" => ItemData {
        num: 1212,
        name: "TR82",
        description: "",
    },
    "tr83" => ItemData {
        num: 1213,
        name: "TR83",
        description: "",
    },
    "tr84" => ItemData {
        num: 1214,
        name: "TR84",
        description: "",
    },
    "tr85" => ItemData {
        num: 1215,
        name: "TR85",
        description: "",
    },
    "tr86" => ItemData {
        num: 1216,
        name: "TR86",
        description: "",
    },
    "tr87" => ItemData {
        num: 1217,
        name: "TR87",
        description: "",
    },
    "tr88" => ItemData {
        num: 1218,
        name: "TR88",
        description: "",
    },
    "tr89" => ItemData {
        num: 1219,
        name: "TR89",
        description: "",
    },
    "tr90" => ItemData {
        num: 1220,
        name: "TR90",
        description: "",
    },
    "tr91" => ItemData {
        num: 1221,
        name: "TR91",
        description: "",
    },
    "tr92" => ItemData {
        num: 1222,
        name: "TR92",
        description: "",
    },
    "tr93" => ItemData {
        num: 1223,
        name: "TR93",
        description: "",
    },
    "tr94" => ItemData {
        num: 1224,
        name: "TR94",
        description: "",
    },
    "tr95" => ItemData {
        num: 1225,
        name: "TR95",
        description: "",
    },
    "tr96" => ItemData {
        num: 1226,
        name: "TR96",
        description: "",
    },
    "tr97" => ItemData {
        num: 1227,
        name: "TR97",
        description: "",
    },
    "tr98" => ItemData {
        num: 1228,
        name: "TR98",
        description: "",
    },
    "tr99" => ItemData {
        num: 1229,
        name: "TR99",
        description: "",
    },
    "crackedpot" => ItemData {
        num: 1253,
        name: "Cracked Pot",
        description: "",
    },
    "chippedpot" => ItemData {
        num: 1254,
        name: "Chipped Pot",
        description: "",
    },
    "galaricacuff" => ItemData {
        num: 1582,
        name: "Galarica Cuff",
        description: "",
    },
    "galaricawreath" => ItemData {
        num: 1592,
        name: "Galarica Wreath",
        description: "",
    },
    "adamantcrystal" => ItemData {
        num: 1777,
        name: "Adamant Crystal",
        description: "",
    },
    "lustrousglobe" => ItemData {
        num: 1778,
        name: "Lustrous Globe",
        description: "",
    },
    "griseouscore" => ItemData {
        num: 1779,
        name: "Griseous Core",
        description: "",
    },
    "strangeball" => ItemData {
        num: 1785,
        name: "Strange Ball",
        description: "",
    },
    "maliciousarmor" => ItemData {
        num: 1861,
        name: "Malicious Armor",
        description: "",
    },
    "boosterenergy" => ItemData {
        num: 1880,
        name: "Booster Energy",
        description: "",
    },
    "abilityshield" => ItemData {
        num: 1881,
        name: "Ability Shield",
        description: "",
    },
    "clearamulet" => ItemData {
        num: 1882,
        name: "Clear Amulet",
        description: "",
    },
    "mirrorherb" => ItemData {
        num: 1883,
        name: "Mirror Herb",
        description: "",
    },
    "punchingglove" => ItemData {
        num: 1884,
        name: "Punching Glove",
        description: "",
    },
    "covertcloak" => ItemData {
        num: 1885,
        name: "Covert Cloak",
        description: "",
    },
    "loadeddice" => ItemData {
        num: 1886,
        name: "Loaded Dice",
        description: "",
    },
    "auspiciousarmor" => ItemData {
        num: 2344,
        name: "Auspicious Armor",
        description: "",
    },
    "fairyfeather" => ItemData {
        num: 2401,
        name: "Fairy Feather",
        description: "",
    },
    "syrupyapple" => ItemData {
        num: 2402,
        name: "Syrupy Apple",
        description: "",
    },
    "unremarkableteacup" => ItemData {
        num: 2403,
        name: "Unremarkable Teacup",
        description: "",
    },
    "masterpieceteacup" => ItemData {
        num: 2404,
        name: "Masterpiece Teacup",
        description: "",
    },
    "cornerstonemask" => ItemData {
        num: 2406,
        name: "Cornerstone Mask",
        description: "",
    },
    "wellspringmask" => ItemData {
        num: 2407,
        name: "Wellspring Mask",
        description: "",
    },
    "hearthflamemask" => ItemData {
        num: 2408,
        name: "Hearthflame Mask",
        description: "",
    },
    "metalalloy" => ItemData {
        num: 2482,
        name: "Metal Alloy",
        description: "",
    },
    "clefablite" => ItemData {
        num: 2559,
        name: "Clefablite",
        description: "",
    },
    "victreebelite" => ItemData {
        num: 2560,
        name: "Victreebelite",
        description: "",
    },
    "starminite" => ItemData {
        num: 2561,
        name: "Starminite",
        description: "",
    },
    "dragoninite" => ItemData {
        num: 2562,
        name: "Dragoninite",
        description: "",
    },
    "meganiumite" => ItemData {
        num: 2563,
        name: "Meganiumite",
        description: "",
    },
    "feraligite" => ItemData {
        num: 2564,
        name: "Feraligite",
        description: "",
    },
    "skarmorite" => ItemData {
        num: 2565,
        name: "Skarmorite",
        description: "",
    },
    "froslassite" => ItemData {
        num: 2566,
        name: "Froslassite",
        description: "",
    },
    "emboarite" => ItemData {
        num: 2569,
        name: "Emboarite",
        description: "",
    },
    "excadrite" => ItemData {
        num: 2570,
        name: "Excadrite",
        description: "",
    },
    "scolipite" => ItemData {
        num: 2571,
        name: "Scolipite",
        description: "",
    },
    "scraftinite" => ItemData {
        num: 2572,
        name: "Scraftinite",
        description: "",
    },
    "eelektrossite" => ItemData {
        num: 2573,
        name: "Eelektrossite",
        description: "",
    },
    "chandelurite" => ItemData {
        num: 2574,
        name: "Chandelurite",
        description: "",
    },
    "chesnaughtite" => ItemData {
        num: 2575,
        name: "Chesnaughtite",
        description: "",
    },
    "delphoxite" => ItemData {
        num: 2576,
        name: "Delphoxite",
        description: "",
    },
    "greninjite" => ItemData {
        num: 2577,
        name: "Greninjite",
        description: "",
    },
    "pyroarite" => ItemData {
        num: 2578,
        name: "Pyroarite",
        description: "",
    },
    "floettite" => ItemData {
        num: 2579,
        name: "Floettite",
        description: "",
    },
    "malamarite" => ItemData {
        num: 2580,
        name: "Malamarite",
        description: "",
    },
    "barbaracite" => ItemData {
        num: 2581,
        name: "Barbaracite",
        description: "",
    },
    "dragalgite" => ItemData {
        num: 2582,
        name: "Dragalgite",
        description: "",
    },
    "hawluchanite" => ItemData {
        num: 2583,
        name: "Hawluchanite",
        description: "",
    },
    "zygardite" => ItemData {
        num: 2584,
        name: "Zygardite",
        description: "",
    },
    "drampanite" => ItemData {
        num: 2585,
        name: "Drampanite",
        description: "",
    },
    "raichunitex" => ItemData {
        num: 2585,
        name: "Raichunite X",
        description: "",
    },
    "falinksite" => ItemData {
        num: 2586,
        name: "Falinksite",
        description: "",
    },
    "raichunitey" => ItemData {
        num: 2586,
        name: "Raichunite Y",
        description: "",
    },
    "chimechite" => ItemData {
        num: 2587,
        name: "Chimechite",
        description: "",
    },
    "absolitez" => ItemData {
        num: 2588,
        name: "Absolite Z",
        description: "",
    },
    "staraptite" => ItemData {
        num: 2589,
        name: "Staraptite",
        description: "",
    },
    "garchompitez" => ItemData {
        num: 2590,
        name: "Garchompite Z",
        description: "",
    },
    "lucarionitez" => ItemData {
        num: 2591,
        name: "Lucarionite Z",
        description: "",
    },
    "heatranite" => ItemData {
        num: 2592,
        name: "Heatranite",
        description: "",
    },
    "darkranite" => ItemData {
        num: 2593,
        name: "Darkranite",
        description: "",
    },
    "golurkite" => ItemData {
        num: 2594,
        name: "Golurkite",
        description: "",
    },
    "meowsticite" => ItemData {
        num: 2594,
        name: "Meowsticite",
        description: "",
    },
    "crabominite" => ItemData {
        num: 2595,
        name: "Crabominite",
        description: "",
    },
    "golisopite" => ItemData {
        num: 2596,
        name: "Golisopite",
        description: "",
    },
    "magearnite" => ItemData {
        num: 2597,
        name: "Magearnite",
        description: "",
    },
    "zeraorite" => ItemData {
        num: 2598,
        name: "Zeraorite",
        description: "",
    },
    "scovillainite" => ItemData {
        num: 2599,
        name: "Scovillainite",
        description: "",
    },
    "glimmoranite" => ItemData {
        num: 2600,
        name: "Glimmoranite",
        description: "",
    },
    "baxcalibrite" => ItemData {
        num: 2601,
        name: "Baxcalibrite",
        description: "",
    },
    "tatsugirinite" => ItemData {
        num: 2601,
        name: "Tatsugirinite",
        description: "",
    },
};
