#!/usr/bin/env node
"use strict";

// 目的: pokemon-showdown/data/items.ts を読み込み、行動順に影響する主要フィールドを抽出し、Rust の静的テーブルとして出力。
// シングル想定かつ主要イベントのみ抽出（fractional priority と速度・火力補正に関わる一部）。
// 参考: data/items.ts の onFractionalPriority / onModifyAtk など。

require("ts-node").register({
  transpileOnly: true,
  compilerOptions: {
    module: "CommonJS",
    moduleResolution: "Node",
    esModuleInterop: true,
    target: "ES2019",
  },
});
const path = require("path");
const { Items } = require(path.resolve(__dirname, "../pokemon-showdown/data/items"));

function normalizeId(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

function extract() {
  const entries = [];
  for (const key in Items) {
    const item = Items[key];
    const id = normalizeId(item.name || key);
    const effect = {
      id,
      name: item.name,
      priorityFrac: null,
      speedMult: null,
      atkMult: null,
      spaMult: null,
      defMult: null,
      spdMult: null,
      lifeOrb: false,
      choiceStat: null,
      sashLike: item.name && item.name.toLowerCase() === "focus sash",
      sturdyLike: false,
    };

    // Fractional priority items
    const onFrac = item.onFractionalPriority;
    if (typeof onFrac === "function" || item.onFractionalPriorityPriority !== undefined) {
      if (id === "quickclaw") {
        effect.priorityFrac = "QuickClaw";
      } else if (id === "custapberry") {
        effect.priorityFrac = "Custap";
      } else if (id === "laggingtail" || id === "fullincense") {
        effect.priorityFrac = "Negative";
      }
    }

    // Choice items
    if (id === "choiceband") effect.choiceStat = "atk";
    if (id === "choicespecs") effect.choiceStat = "spa";
    if (id === "choicescarf") effect.choiceStat = "spe";

    // Life Orb
    if (id === "lifeorb") effect.lifeOrb = true;

    // Basic multipliers commonly used
    if (id === "choicescarf") effect.speedMult = 1.5;
    if (id === "ironball") effect.speedMult = 0.5;
    if (id === "quickpowder") effect.speedMult = 2.0;

    if (id === "choiceband") effect.atkMult = 1.5;
    if (id === "choicespecs") effect.spaMult = 1.5;

    entries.push(effect);
  }
  return entries;
}

function renderRust(entries) {
  const lines = [];
  lines.push("// AUTO-GENERATED by tools/extract_items.js");
  lines.push("pub static ITEM_TABLE: phf::Map<&'static str, ItemEffect> = phf::phf_map! {");
  for (const eff of entries) {
    lines.push(
      `    "${eff.id}" => ItemEffect {` +
        ` name: "${eff.name.replace(/"/g, '\\"')}",` +
        ` priority_frac: ${renderPriority(eff.priorityFrac)},` +
        ` speed_mult: ${renderOptFloat(eff.speedMult)},` +
        ` atk_mult: ${renderOptFloat(eff.atkMult)},` +
        ` spa_mult: ${renderOptFloat(eff.spaMult)},` +
        ` def_mult: ${renderOptFloat(eff.defMult)},` +
        ` spd_mult: ${renderOptFloat(eff.spdMult)},` +
        ` life_orb: ${eff.lifeOrb},` +
        ` choice_stat: ${renderChoiceStat(eff.choiceStat)},` +
        ` sash_like: ${eff.sashLike},` +
        ` sturdy_like: ${eff.sturdyLike},` +
      " },"
    );
  }
  lines.push("};");
  return lines.join("\n");
}

function renderPriority(p) {
  if (!p) return "None";
  return `Some(PriorityEffect::${p})`;
}
function renderOptFloat(v) {
  if (v == null) return "None";
  const s = Number.isInteger(v) ? `${v}.0` : `${v}`;
  return `Some(${s})`;
}
function renderChoiceStat(s) {
  if (!s) return "None";
  return `Some("${s}")`;
}

const data = extract();
process.stdout.write(renderRust(data));
